import type { Project, Task, Decision, TimeBlock } from "./types";
import { isoDate } from "./utils";

// Generic demo data — loaded via the command palette "Load demo data" action.
// Feel free to replace all of this with your own seed if you fork.

const today = new Date();
const iso = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return isoDate(d);
};

export const seedProjects: Project[] = [
  {
    id: "proj_side_app",
    name: "Side project app",
    type: "code",
    state: "active",
    oneLiner: "The app you're always almost shipping.",
    accentColor: "#14b8a6",
    nextAction: "Wire up auth on the onboarding screen.",
    stack: ["React", "TypeScript", "Supabase"],
    lastTouchedAt: new Date(today.getTime() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: iso(-60),
  },
  {
    id: "proj_dashboard",
    name: "Cockpit",
    type: "code",
    state: "active",
    oneLiner: "This thing. Personal dashboard for project + day planning.",
    accentColor: "#f59e0b",
    nextAction: "Ship the today view and planner.",
    stack: ["Vite", "React", "TypeScript", "Tailwind"],
    lastTouchedAt: new Date(today.getTime() - 1000 * 60 * 15).toISOString(),
    createdAt: iso(-2),
  },
  {
    id: "proj_client_work",
    name: "Client — redesign",
    type: "business",
    state: "active",
    oneLiner: "Current client engagement. Deliverables due in two weeks.",
    accentColor: "#8b5cf6",
    nextAction: "Review the latest design pass with the team.",
    client: "Acme Co.",
    dueDate: iso(14),
    lastTouchedAt: new Date(today.getTime() - 1000 * 60 * 60 * 26).toISOString(),
    createdAt: iso(-120),
  },
  {
    id: "proj_automation",
    name: "Automation storefront",
    type: "code",
    state: "on_hold",
    oneLiner: "Pre-built bots you can clone — on ice until the flagship ships.",
    accentColor: "#0ea5e9",
    resumeNote: "Come back once the flagship app is live. Need the case study.",
    nextAction: "Pick 3 bots to productize first.",
    stack: ["Next.js", "Supabase", "Stripe"],
    lastTouchedAt: iso(-12),
    createdAt: iso(-45),
  },
  {
    id: "proj_trip",
    name: "Big trip",
    type: "life",
    state: "on_hold",
    oneLiner: "Two weeks abroad. Planning paused.",
    accentColor: "#f43f5e",
    resumeNote: "Pick back up after the client deliverable.",
    nextAction: "Book transit passes.",
    dueDate: iso(90),
    lastTouchedAt: iso(-8),
    createdAt: iso(-30),
  },
  {
    id: "proj_portfolio",
    name: "Portfolio refresh",
    type: "code",
    state: "waiting",
    oneLiner: "Redesign personal site. Case studies + writing.",
    accentColor: "#84cc16",
    nextAction: "Decide stack — Astro vs Next.",
    stack: ["TBD"],
    lastTouchedAt: iso(-20),
    createdAt: iso(-20),
  },
  {
    id: "proj_newsletter",
    name: "Weekly newsletter",
    type: "business",
    state: "waiting",
    oneLiner: "Build-in-public weekly on solo-dev AI work.",
    accentColor: "#f59e0b",
    nextAction: "Outline the first 6 issues.",
    lastTouchedAt: iso(-5),
    createdAt: iso(-5),
  },
  {
    id: "proj_prev_saas",
    name: "Previous SaaS",
    type: "code",
    state: "shipped",
    oneLiner: "A small product that shipped and found 200 users.",
    accentColor: "#14b8a6",
    stack: ["Next.js", "Supabase"],
    lastTouchedAt: iso(-90),
    createdAt: iso(-240),
  },
];

export const seedTasks: Task[] = [
  {
    id: "task_1",
    title: "Ship auth on the onboarding screen",
    status: "doing",
    projectId: "proj_side_app",
    energyTag: "deep",
    timeEstimate: 120,
    scheduledFor: iso(0),
    recurrence: "none",
    createdAt: iso(-1),
  },
  {
    id: "task_2",
    title: "Draft the Planner drag-drop logic",
    status: "todo",
    projectId: "proj_dashboard",
    energyTag: "deep",
    timeEstimate: 90,
    scheduledFor: iso(0),
    recurrence: "none",
    createdAt: iso(-1),
  },
  {
    id: "task_3",
    title: "Review the latest design pass with the team",
    status: "todo",
    projectId: "proj_client_work",
    energyTag: "social",
    timeEstimate: 30,
    scheduledFor: iso(0),
    recurrence: "none",
    createdAt: iso(-2),
  },
  {
    id: "task_4",
    title: "Pay monthly SaaS invoices",
    status: "todo",
    energyTag: "grunt",
    timeEstimate: 15,
    scheduledFor: iso(0),
    recurrence: "none",
    createdAt: iso(-1),
  },
  {
    id: "task_5",
    title: "Morning review — inbox + planner",
    status: "todo",
    energyTag: "thinky",
    timeEstimate: 10,
    recurrence: "daily",
    scheduledFor: iso(0),
    createdAt: iso(-7),
  },
  {
    id: "task_6",
    title: "Weekly review — what shipped, what stalled",
    status: "todo",
    energyTag: "thinky",
    timeEstimate: 30,
    recurrence: "weekly",
    scheduledFor: iso(3),
    createdAt: iso(-14),
  },
  {
    id: "task_7",
    title: "Fix the map crash on Android",
    status: "todo",
    projectId: "proj_side_app",
    energyTag: "deep",
    timeEstimate: 90,
    recurrence: "none",
    createdAt: iso(-3),
  },
  {
    id: "task_8",
    title: "Call the dentist",
    status: "todo",
    energyTag: "social",
    timeEstimate: 10,
    dueDate: iso(2),
    recurrence: "none",
    createdAt: iso(-1),
  },
  {
    id: "task_9",
    title: "Prep project detail page",
    status: "done",
    projectId: "proj_dashboard",
    energyTag: "deep",
    timeEstimate: 60,
    recurrence: "none",
    createdAt: iso(-1),
    completedAt: new Date(today.getTime() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "task_10",
    title: "Sketch out dashboard component tree",
    status: "done",
    projectId: "proj_dashboard",
    energyTag: "thinky",
    timeEstimate: 45,
    recurrence: "none",
    createdAt: iso(-2),
    completedAt: iso(-1),
  },
];

export const seedDecisions: Decision[] = [
  {
    id: "dec_1",
    projectId: "proj_dashboard",
    date: iso(-1),
    what: "Use localStorage over a backend for v1",
    why: "Ship faster, avoid backend setup while the UX is still churning.",
  },
  {
    id: "dec_2",
    projectId: "proj_dashboard",
    date: iso(-1),
    what: "Tasks can live standalone or on a project",
    why: "One inbox covers life + project tasks without a separate routines table.",
  },
  {
    id: "dec_3",
    projectId: "proj_side_app",
    date: iso(-5),
    what: "Swap maps library for native equivalent",
    why: "Better performance on low-end devices + no per-seat pricing.",
  },
];

export const seedBlocks: TimeBlock[] = [
  {
    id: "blk_1",
    date: iso(0),
    start: "09:00",
    end: "11:00",
    label: "Deep work",
    energyTag: "deep",
    taskIds: ["task_1"],
    projectId: "proj_side_app",
  },
  {
    id: "blk_2",
    date: iso(0),
    start: "11:15",
    end: "12:30",
    label: "Dashboard build",
    energyTag: "deep",
    taskIds: ["task_2"],
    projectId: "proj_dashboard",
  },
  {
    id: "blk_3",
    date: iso(0),
    start: "14:00",
    end: "14:30",
    label: "Client touchpoints",
    energyTag: "social",
    taskIds: ["task_3"],
    projectId: "proj_client_work",
  },
  {
    id: "blk_4",
    date: iso(0),
    start: "16:00",
    end: "16:30",
    label: "Admin / grunt",
    energyTag: "grunt",
    taskIds: ["task_4"],
  },
];

